"use client";

import { createContext, useContext, useEffect, useMemo } from "react";

const copy = {
  en: {
    govt: "Government of Kerala", dept: "Labour & Skills Department", appName: "Worker Health Service", appTag: "Health ID and insurance help", helpline: "Help line", skip: "Skip to main content", home: "Home", services: "Services", claims: "My claims", help: "Help", safety: "Keep your OTP and Aadhaar number private.", footerLine: "A service of the Labour & Skills Department, Government of Kerala.", quickLinks: "Quick links", needHelp: "Need help?", hours: "Monday–Saturday, 8 AM–8 PM", copyright: "Government of Kerala",
    welcomeTag: "Health and insurance help", welcomeTitle: "Your health card and claims, in one place", welcomeBody: "Get your worker health ID, show it at a clinic, and check your insurance claim.", chooseLanguage: "Choose your language", newWorker: "I need a new ID", haveId: "I already have an ID", secureServices: "Your services", onePlace: "Simple and secure", digitalId: "Health ID card", digitalDesc: "Show your QR card at a clinic.", treatmentHelp: "Treatment help", treatmentDesc: "Get sent to the right hospital when needed.", claimTracking: "Claim status", claimDesc: "See if your claim is checking, approved, or paid.", privacy: "Your full Aadhaar number is never shown here.", abhaLinked: "ABHA linked", abhaText: "Health records", aawazActive: "Aawaz active", aawazText: "Worker insurance", claimHelp: "Claim help", claimHelpText: "Status and complaints",
    back: "Go back", required: "Required", registerTag: "New worker", registerTitle: "Get your worker health ID", registerDesc: "Keep your Aadhaar and e-Shram card ready.", step1: "Enter your details", asOnCards: "Copy them from your cards", aadhaar: "Aadhaar number", aadhaarPlaceholder: "12-digit Aadhaar number", aadhaarHelp: "We use this only to check your identity.", eshram: "e-Shram number", eshramPlaceholder: "Enter e-Shram number", step2: "Check your fingerprint", fingerHelp: "Use the fingerprint scanner", capture: "Scan fingerprint", captured: "Fingerprint scanned", capturedHelp: "Your fingerprint was received", placeFinger: "Place your finger on the scanner", consent: "I agree to use these details for health and insurance services.", verify: "Check details and continue", beforeBegin: "Keep these ready", ready1: "Aadhaar card", ready2: "e-Shram card", ready3: "Phone linked to your records", callHelp: "For help, call",
    loginTag: "Welcome back", loginTitle: "Open your account", loginDesc: "Use your e-Shram number and the code sent to your phone.", otp: "Phone code (OTP)", otpPlaceholder: "Enter phone code", signIn: "Open my account", loginHint: "The phone code has 6 digits.", regFailTitle: "We could not check your details", regFailText: "Check the Aadhaar and e-Shram numbers, then try again.", loginFailTitle: "We could not open your account", loginFailText: "Check your e-Shram number and phone code, then try again.", tryAgain: "Try again", returnHome: "Go to home",
    regDone: "ID ready", verifiedTitle: "Your worker ID is ready", linkedText: "Your health and insurance services are linked.", workerId: "Worker ID", abhaId: "ABHA health ID", aawazId: "Aawaz insurance", linked: "Linked", openDashboard: "Continue",
    dashboard: "My services", welcome: "Hello", dashboardDesc: "What do you want to do?", verifiedAccount: "Verified", citizenServices: "Choose a service", showId: "Show my health ID", showIdText: "Use this QR card at a clinic.", trackClaims: "Check my claims", trackClaimsText: "See claim status and payment.", healthRecords: "Health records", healthRecordsText: "See linked treatment records.", findFacility: "Find a hospital", findFacilityText: "Find nearby care.", comingSoon: "Available soon", coverage: "My links", accountCheck: "Account", active: "Active", important: "Remember", showBefore: "Show your health ID before treatment starts.",
    idTag: "My health ID", idTitle: "Show this card at the clinic", idDesc: "The clinic can scan this QR code.", validFacilities: "Verified health service ID", clinicAction: "At the clinic", clinicActionText: "Ask the clinic to scan this card before treatment.", scan: "Scan card", referralTag: "Next step", referralTitle: "Go to this government hospital", referralDesc: "A doctor must check your treatment before the claim can continue.", nearestHospital: "Nearest government hospital", defaultHospital:"Government Taluk Hospital, Kochi", referralDesk: "Ask for the referral desk", directions: "Open map for directions", atHospital: "What to do", hospital1: "Show your worker health ID.", hospital2: "Show your treatment paper.", hospital3: "Ask the doctor to check the claim.", doctorVerify: "Doctor has checked it",
    claimsTag: "My insurance", claimsTitle: "My claims", claimsDesc: "Tap a claim to see more.", records: "claims", loadingClaims: "Loading claims…", noClaims: "No claims yet", noClaimsText: "A new claim will show here after a clinic sends it.", claimAmount: "Amount", dateUnavailable: "Date not available", claimDetails: "Claim details", updated: "Updated", currentStatus: "Current status", progress: "What is happening", submitted: "Sent", checking: "Checking", approved: "Approved", paid: "Paid", rejected: "Rejected", rejectionReason: "Why it was rejected", rejectedDefault: "The insurance office could not approve this claim.", availableAction: "What you can do", disputeHelp: "If the information is wrong, ask for another check.", raiseDispute: "Ask for another check", noAction: "You do not need to do anything now. We will update this status.", grievance: "Claim help", disputeTitle: "Ask us to check again", disputeDesc: "Claim {id}", rejectedClaim: "Rejected claim", explain: "Tell us what is wrong", explainPlaceholder: "Write what happened. A helper can type this for you.", explainHelp: "Do not write your OTP or full Aadhaar number.", submitDispute: "Send request", disputeSent: "Request sent", disputeSentText: "We will check your claim again.", reference: "Reference number", returnClaim: "Back to claim",
    errorClaims: "Claims could not be loaded. Try again.", errorClaim: "This claim could not be opened. Try again.", errorTreatment: "Treatment could not be sent. Try again.", errorVerify: "The doctor check could not be saved. Try again.", errorDispute: "Your request could not be sent. Try again.", dismiss: "Close message", otpHelp: "Your phone code is 123456.", errorConfig: "The app is not connected to a server yet.", chooseFacility: "Choose the clinic or hospital", chooseFacilityHelp: "Select where the worker received treatment.", abhaFacility: "ABHA linked", referralFacility: "Doctor check needed", treatmentCost: "Treatment cost", treatmentCostHelp: "Enter the amount in rupees.", scanSelected: "Send treatment", qrAlt: "QR code for worker health ID", claimAria: "Claim {id}, {status}, amount {amount} rupees"
  },
  hi: {
    govt:"केरल सरकार",dept:"श्रम एवं कौशल विभाग",appName:"श्रमिक स्वास्थ्य सेवा",appTag:"स्वास्थ्य आईडी और बीमा सहायता",helpline:"सहायता नंबर",skip:"मुख्य भाग पर जाएँ",home:"होम",services:"सेवाएँ",claims:"मेरे क्लेम",help:"सहायता",safety:"अपना OTP और आधार नंबर किसी को न बताएँ।",footerLine:"केरल सरकार के श्रम एवं कौशल विभाग की सेवा।",quickLinks:"ज़रूरी लिंक",needHelp:"सहायता चाहिए?",hours:"सोमवार–शनिवार, सुबह 8–रात 8",copyright:"केरल सरकार",
    welcomeTag:"स्वास्थ्य और बीमा सहायता",welcomeTitle:"आपका स्वास्थ्य कार्ड और क्लेम, एक ही जगह",welcomeBody:"श्रमिक स्वास्थ्य आईडी बनाएँ, क्लिनिक में दिखाएँ और बीमा क्लेम देखें।",chooseLanguage:"अपनी भाषा चुनें",newWorker:"मुझे नई आईडी चाहिए",haveId:"मेरे पास आईडी है",secureServices:"आपकी सेवाएँ",onePlace:"सरल और सुरक्षित",digitalId:"स्वास्थ्य आईडी कार्ड",digitalDesc:"क्लिनिक में QR कार्ड दिखाएँ।",treatmentHelp:"इलाज में सहायता",treatmentDesc:"ज़रूरत पर सही अस्पताल जाएँ।",claimTracking:"क्लेम की स्थिति",claimDesc:"देखें क्लेम जाँच में, मंज़ूर या भुगतान हुआ है।",privacy:"आपका पूरा आधार नंबर यहाँ कभी नहीं दिखता।",abhaLinked:"ABHA जुड़ा है",abhaText:"स्वास्थ्य रिकॉर्ड",aawazActive:"आवाज़ सक्रिय",aawazText:"श्रमिक बीमा",claimHelp:"क्लेम सहायता",claimHelpText:"स्थिति और शिकायत",
    back:"पीछे जाएँ",required:"ज़रूरी",registerTag:"नया श्रमिक",registerTitle:"अपनी श्रमिक स्वास्थ्य आईडी बनाएँ",registerDesc:"आधार और ई-श्रम कार्ड पास रखें।",step1:"अपनी जानकारी भरें",asOnCards:"कार्ड देखकर सही-सही लिखें",aadhaar:"आधार नंबर",aadhaarPlaceholder:"12 अंकों का आधार नंबर",aadhaarHelp:"इसका उपयोग केवल पहचान जाँचने के लिए होगा।",eshram:"ई-श्रम नंबर",eshramPlaceholder:"ई-श्रम नंबर लिखें",step2:"फिंगरप्रिंट जाँचें",fingerHelp:"फिंगरप्रिंट स्कैनर का उपयोग करें",capture:"फिंगरप्रिंट स्कैन करें",captured:"फिंगरप्रिंट स्कैन हो गया",capturedHelp:"फिंगरप्रिंट मिल गया",placeFinger:"स्कैनर पर उंगली रखें",consent:"मैं स्वास्थ्य और बीमा सेवा के लिए इन जानकारियों के उपयोग से सहमत हूँ।",verify:"जानकारी जाँचें और आगे बढ़ें",beforeBegin:"ये चीज़ें पास रखें",ready1:"आधार कार्ड",ready2:"ई-श्रम कार्ड",ready3:"रिकॉर्ड से जुड़ा फोन",callHelp:"सहायता के लिए कॉल करें",
    loginTag:"फिर से स्वागत है",loginTitle:"अपना खाता खोलें",loginDesc:"ई-श्रम नंबर और फोन पर आया कोड लिखें।",otp:"फोन कोड (OTP)",otpPlaceholder:"फोन कोड लिखें",signIn:"मेरा खाता खोलें",loginHint:"फोन कोड 6 अंकों का होता है।",regFailTitle:"जानकारी की जाँच नहीं हो सकी",regFailText:"आधार और ई-श्रम नंबर जाँचकर फिर कोशिश करें।",loginFailTitle:"खाता नहीं खुल सका",loginFailText:"ई-श्रम नंबर और फोन कोड जाँचकर फिर कोशिश करें।",tryAgain:"फिर कोशिश करें",returnHome:"होम पर जाएँ",
    regDone:"आईडी तैयार",verifiedTitle:"आपकी श्रमिक आईडी तैयार है",linkedText:"स्वास्थ्य और बीमा सेवाएँ जुड़ गई हैं।",workerId:"श्रमिक आईडी",abhaId:"ABHA स्वास्थ्य आईडी",aawazId:"आवाज़ बीमा",linked:"जुड़ा है",openDashboard:"आगे बढ़ें",
    dashboard:"मेरी सेवाएँ",welcome:"नमस्ते",dashboardDesc:"आप क्या करना चाहते हैं?",verifiedAccount:"सत्यापित",citizenServices:"एक सेवा चुनें",showId:"मेरी स्वास्थ्य आईडी दिखाएँ",showIdText:"क्लिनिक में यह QR कार्ड दिखाएँ।",trackClaims:"मेरे क्लेम देखें",trackClaimsText:"स्थिति और भुगतान देखें।",healthRecords:"स्वास्थ्य रिकॉर्ड",healthRecordsText:"जुड़े इलाज के रिकॉर्ड देखें।",findFacility:"अस्पताल खोजें",findFacilityText:"पास में इलाज खोजें।",comingSoon:"जल्द उपलब्ध",coverage:"मेरे लिंक",accountCheck:"खाता",active:"सक्रिय",important:"याद रखें",showBefore:"इलाज शुरू होने से पहले स्वास्थ्य आईडी दिखाएँ।",
    idTag:"मेरी स्वास्थ्य आईडी",idTitle:"क्लिनिक में यह कार्ड दिखाएँ",idDesc:"क्लिनिक इस QR कोड को स्कैन कर सकता है।",validFacilities:"सत्यापित स्वास्थ्य सेवा आईडी",clinicAction:"क्लिनिक में",clinicActionText:"इलाज से पहले क्लिनिक से यह कार्ड स्कैन करने को कहें।",scan:"कार्ड स्कैन करें",referralTag:"अगला कदम",referralTitle:"इस सरकारी अस्पताल जाएँ",referralDesc:"क्लेम आगे बढ़ने से पहले डॉक्टर इलाज की जाँच करेंगे।",nearestHospital:"सबसे पास सरकारी अस्पताल",defaultHospital:"सरकारी तालुक अस्पताल, कोच्चि",referralDesk:"रेफरल डेस्क पर जाएँ",directions:"रास्ता देखने के लिए नक्शा खोलें",atHospital:"क्या करना है",hospital1:"श्रमिक स्वास्थ्य आईडी दिखाएँ।",hospital2:"इलाज का कागज़ दिखाएँ।",hospital3:"डॉक्टर से क्लेम जाँचने को कहें।",doctorVerify:"डॉक्टर ने जाँच कर ली",
    claimsTag:"मेरा बीमा",claimsTitle:"मेरे क्लेम",claimsDesc:"अधिक जानकारी के लिए क्लेम पर टैप करें।",records:"क्लेम",loadingClaims:"क्लेम लोड हो रहे हैं…",noClaims:"अभी कोई क्लेम नहीं",noClaimsText:"क्लिनिक के भेजने के बाद नया क्लेम यहाँ दिखेगा।",claimAmount:"राशि",dateUnavailable:"तारीख उपलब्ध नहीं",claimDetails:"क्लेम की जानकारी",updated:"अंतिम बदलाव",currentStatus:"अभी की स्थिति",progress:"क्या हो रहा है",submitted:"भेजा गया",checking:"जाँच जारी",approved:"मंज़ूर",paid:"भुगतान हुआ",rejected:"नामंज़ूर",rejectionReason:"नामंज़ूर होने का कारण",rejectedDefault:"बीमा कार्यालय इस क्लेम को मंज़ूर नहीं कर सका।",availableAction:"आप क्या कर सकते हैं",disputeHelp:"जानकारी गलत हो तो दोबारा जाँच माँगें।",raiseDispute:"दोबारा जाँच माँगें",noAction:"अभी आपको कुछ नहीं करना है। स्थिति यहाँ बदल जाएगी।",grievance:"क्लेम सहायता",disputeTitle:"दोबारा जाँच के लिए कहें",disputeDesc:"क्लेम {id}",rejectedClaim:"नामंज़ूर क्लेम",explain:"बताएँ क्या गलत है",explainPlaceholder:"क्या हुआ लिखें। कोई सहायक आपके लिए लिख सकता है।",explainHelp:"OTP या पूरा आधार नंबर न लिखें।",submitDispute:"अनुरोध भेजें",disputeSent:"अनुरोध भेज दिया गया",disputeSentText:"हम क्लेम की दोबारा जाँच करेंगे।",reference:"संदर्भ नंबर",returnClaim:"क्लेम पर वापस जाएँ",
    errorClaims:"क्लेम लोड नहीं हुए। फिर कोशिश करें।",errorClaim:"क्लेम नहीं खुला। फिर कोशिश करें।",errorTreatment:"इलाज की जानकारी नहीं भेजी गई। फिर कोशिश करें।",errorVerify:"डॉक्टर की जाँच सेव नहीं हुई। फिर कोशिश करें।",errorDispute:"अनुरोध नहीं भेजा गया। फिर कोशिश करें।",dismiss:"संदेश बंद करें",otpHelp:"आपका फोन कोड 123456 है।",errorConfig:"ऐप अभी सर्वर से जुड़ा नहीं है।",chooseFacility:"क्लिनिक या अस्पताल चुनें",chooseFacilityHelp:"जहाँ श्रमिक का इलाज हुआ, वह जगह चुनें।",abhaFacility:"ABHA से जुड़ा",referralFacility:"डॉक्टर की जाँच ज़रूरी",treatmentCost:"इलाज का खर्च",treatmentCostHelp:"रुपयों में राशि लिखें।",scanSelected:"इलाज की जानकारी भेजें",qrAlt:"श्रमिक स्वास्थ्य आईडी का QR कोड",claimAria:"क्लेम {id}, {status}, राशि {amount} रुपये"
  },
  ml: {
    govt:"കേരള സർക്കാർ",dept:"തൊഴിലും നൈപുണ്യവും വകുപ്പ്",appName:"തൊഴിലാളി ആരോഗ്യ സേവനം",appTag:"ആരോഗ്യ ഐഡിയും ഇൻഷുറൻസ് സഹായവും",helpline:"സഹായ നമ്പർ",skip:"പ്രധാന ഭാഗത്തേക്ക് പോകുക",home:"ഹോം",services:"സേവനങ്ങൾ",claims:"എന്റെ ക്ലെയിമുകൾ",help:"സഹായം",safety:"OTPയും ആധാർ നമ്പറും ആരോടും പറയരുത്.",footerLine:"കേരള സർക്കാർ തൊഴിലും നൈപുണ്യവും വകുപ്പിന്റെ സേവനം.",quickLinks:"പ്രധാന ലിങ്കുകൾ",needHelp:"സഹായം വേണോ?",hours:"തിങ്കൾ–ശനി, രാവിലെ 8–രാത്രി 8",copyright:"കേരള സർക്കാർ",
    welcomeTag:"ആരോഗ്യ, ഇൻഷുറൻസ് സഹായം",welcomeTitle:"ആരോഗ്യ കാർഡും ക്ലെയിമുകളും ഒരിടത്ത്",welcomeBody:"തൊഴിലാളി ആരോഗ്യ ഐഡി നേടുക, ക്ലിനിക്കിൽ കാണിക്കുക, ഇൻഷുറൻസ് ക്ലെയിം പരിശോധിക്കുക.",chooseLanguage:"നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",newWorker:"എനിക്ക് പുതിയ ഐഡി വേണം",haveId:"എനിക്ക് ഐഡി ഉണ്ട്",secureServices:"നിങ്ങളുടെ സേവനങ്ങൾ",onePlace:"ലളിതവും സുരക്ഷിതവും",digitalId:"ആരോഗ്യ ഐഡി കാർഡ്",digitalDesc:"ക്ലിനിക്കിൽ QR കാർഡ് കാണിക്കുക.",treatmentHelp:"ചികിത്സാ സഹായം",treatmentDesc:"ആവശ്യമെങ്കിൽ ശരിയായ ആശുപത്രിയിലേക്ക് പോകുക.",claimTracking:"ക്ലെയിം നില",claimDesc:"ക്ലെയിം പരിശോധനയിലാണോ, അംഗീകരിച്ചോ, പണം നൽകിയോ എന്ന് കാണുക.",privacy:"നിങ്ങളുടെ മുഴുവൻ ആധാർ നമ്പർ ഇവിടെ കാണിക്കില്ല.",abhaLinked:"ABHA ബന്ധിപ്പിച്ചു",abhaText:"ആരോഗ്യ രേഖകൾ",aawazActive:"ആവാസ് സജീവം",aawazText:"തൊഴിലാളി ഇൻഷുറൻസ്",claimHelp:"ക്ലെയിം സഹായം",claimHelpText:"നിലയും പരാതിയും",
    back:"പിന്നോട്ട്",required:"നിർബന്ധം",registerTag:"പുതിയ തൊഴിലാളി",registerTitle:"തൊഴിലാളി ആരോഗ്യ ഐഡി നേടുക",registerDesc:"ആധാർ, ഇ-ശ്രം കാർഡുകൾ കൈയിൽ വയ്ക്കുക.",step1:"വിവരങ്ങൾ നൽകുക",asOnCards:"കാർഡിലുള്ളതുപോലെ എഴുതുക",aadhaar:"ആധാർ നമ്പർ",aadhaarPlaceholder:"12 അക്ക ആധാർ നമ്പർ",aadhaarHelp:"തിരിച്ചറിയൽ പരിശോധിക്കാൻ മാത്രം ഉപയോഗിക്കുന്നു.",eshram:"ഇ-ശ്രം നമ്പർ",eshramPlaceholder:"ഇ-ശ്രം നമ്പർ നൽകുക",step2:"വിരലടയാളം പരിശോധിക്കുക",fingerHelp:"വിരലടയാള സ്കാനർ ഉപയോഗിക്കുക",capture:"വിരലടയാളം സ്കാൻ ചെയ്യുക",captured:"വിരലടയാളം സ്കാൻ ചെയ്തു",capturedHelp:"വിരലടയാളം ലഭിച്ചു",placeFinger:"സ്കാനറിൽ വിരൽ വയ്ക്കുക",consent:"ആരോഗ്യ, ഇൻഷുറൻസ് സേവനങ്ങൾക്ക് ഈ വിവരങ്ങൾ ഉപയോഗിക്കാൻ ഞാൻ സമ്മതിക്കുന്നു.",verify:"വിവരങ്ങൾ പരിശോധിച്ച് തുടരുക",beforeBegin:"ഇവ കൈയിൽ വയ്ക്കുക",ready1:"ആധാർ കാർഡ്",ready2:"ഇ-ശ്രം കാർഡ്",ready3:"രേഖകളുമായി ബന്ധിപ്പിച്ച ഫോൺ",callHelp:"സഹായത്തിന് വിളിക്കുക",
    loginTag:"വീണ്ടും സ്വാഗതം",loginTitle:"അക്കൗണ്ട് തുറക്കുക",loginDesc:"ഇ-ശ്രം നമ്പറും ഫോണിൽ വന്ന കോഡും നൽകുക.",otp:"ഫോൺ കോഡ് (OTP)",otpPlaceholder:"ഫോൺ കോഡ് നൽകുക",signIn:"എന്റെ അക്കൗണ്ട് തുറക്കുക",loginHint:"ഫോൺ കോഡിൽ 6 അക്കങ്ങളുണ്ട്.",regFailTitle:"വിവരങ്ങൾ പരിശോധിക്കാനായില്ല",regFailText:"ആധാർ, ഇ-ശ്രം നമ്പറുകൾ പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.",loginFailTitle:"അക്കൗണ്ട് തുറക്കാനായില്ല",loginFailText:"ഇ-ശ്രം നമ്പറും ഫോൺ കോഡും പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.",tryAgain:"വീണ്ടും ശ്രമിക്കുക",returnHome:"ഹോമിലേക്ക് പോകുക",
    regDone:"ഐഡി തയ്യാർ",verifiedTitle:"തൊഴിലാളി ഐഡി തയ്യാറായി",linkedText:"ആരോഗ്യ, ഇൻഷുറൻസ് സേവനങ്ങൾ ബന്ധിപ്പിച്ചു.",workerId:"തൊഴിലാളി ഐഡി",abhaId:"ABHA ആരോഗ്യ ഐഡി",aawazId:"ആവാസ് ഇൻഷുറൻസ്",linked:"ബന്ധിപ്പിച്ചു",openDashboard:"തുടരുക",
    dashboard:"എന്റെ സേവനങ്ങൾ",welcome:"നമസ്കാരം",dashboardDesc:"എന്താണ് ചെയ്യേണ്ടത്?",verifiedAccount:"പരിശോധിച്ചു",citizenServices:"ഒരു സേവനം തിരഞ്ഞെടുക്കുക",showId:"എന്റെ ആരോഗ്യ ഐഡി കാണിക്കുക",showIdText:"ക്ലിനിക്കിൽ ഈ QR കാർഡ് കാണിക്കുക.",trackClaims:"എന്റെ ക്ലെയിമുകൾ കാണുക",trackClaimsText:"നിലയും പണമടച്ചതും കാണുക.",healthRecords:"ആരോഗ്യ രേഖകൾ",healthRecordsText:"ബന്ധിപ്പിച്ച ചികിത്സാ രേഖകൾ കാണുക.",findFacility:"ആശുപത്രി കണ്ടെത്തുക",findFacilityText:"അടുത്തുള്ള ചികിത്സ കണ്ടെത്തുക.",comingSoon:"ഉടൻ ലഭിക്കും",coverage:"എന്റെ ലിങ്കുകൾ",accountCheck:"അക്കൗണ്ട്",active:"സജീവം",important:"ഓർക്കുക",showBefore:"ചികിത്സ തുടങ്ങുന്നതിന് മുമ്പ് ആരോഗ്യ ഐഡി കാണിക്കുക.",
    idTag:"എന്റെ ആരോഗ്യ ഐഡി",idTitle:"ക്ലിനിക്കിൽ ഈ കാർഡ് കാണിക്കുക",idDesc:"ക്ലിനിക്കിന് ഈ QR കോഡ് സ്കാൻ ചെയ്യാം.",validFacilities:"പരിശോധിച്ച ആരോഗ്യ സേവന ഐഡി",clinicAction:"ക്ലിനിക്കിൽ",clinicActionText:"ചികിത്സയ്ക്ക് മുമ്പ് ഈ കാർഡ് സ്കാൻ ചെയ്യാൻ പറയുക.",scan:"കാർഡ് സ്കാൻ ചെയ്യുക",referralTag:"അടുത്ത ഘട്ടം",referralTitle:"ഈ സർക്കാർ ആശുപത്രിയിൽ പോകുക",referralDesc:"ക്ലെയിം തുടരുന്നതിന് മുമ്പ് ഡോക്ടർ ചികിത്സ പരിശോധിക്കണം.",nearestHospital:"അടുത്ത സർക്കാർ ആശുപത്രി",defaultHospital:"സർക്കാർ താലൂക്ക് ആശുപത്രി, കൊച്ചി",referralDesk:"റഫറൽ ഡെസ്കിൽ പോകുക",directions:"വഴി കാണാൻ മാപ്പ് തുറക്കുക",atHospital:"എന്ത് ചെയ്യണം",hospital1:"തൊഴിലാളി ആരോഗ്യ ഐഡി കാണിക്കുക.",hospital2:"ചികിത്സാ കടലാസ് കാണിക്കുക.",hospital3:"ക്ലെയിം പരിശോധിക്കാൻ ഡോക്ടറോട് പറയുക.",doctorVerify:"ഡോക്ടർ പരിശോധിച്ചു",
    claimsTag:"എന്റെ ഇൻഷുറൻസ്",claimsTitle:"എന്റെ ക്ലെയിമുകൾ",claimsDesc:"കൂടുതൽ കാണാൻ ക്ലെയിമിൽ തൊടുക.",records:"ക്ലെയിമുകൾ",loadingClaims:"ക്ലെയിമുകൾ എടുക്കുന്നു…",noClaims:"ക്ലെയിമുകളില്ല",noClaimsText:"ക്ലിനിക് അയച്ച ശേഷം പുതിയ ക്ലെയിം ഇവിടെ കാണും.",claimAmount:"തുക",dateUnavailable:"തീയതി ലഭ്യമല്ല",claimDetails:"ക്ലെയിം വിവരങ്ങൾ",updated:"പുതുക്കിയത്",currentStatus:"ഇപ്പോഴത്തെ നില",progress:"എന്താണ് നടക്കുന്നത്",submitted:"അയച്ചു",checking:"പരിശോധിക്കുന്നു",approved:"അംഗീകരിച്ചു",paid:"പണം നൽകി",rejected:"നിരസിച്ചു",rejectionReason:"നിരസിച്ചതിന്റെ കാരണം",rejectedDefault:"ഇൻഷുറൻസ് ഓഫീസിന് ക്ലെയിം അംഗീകരിക്കാനായില്ല.",availableAction:"നിങ്ങൾക്ക് ചെയ്യാവുന്നത്",disputeHelp:"വിവരം തെറ്റാണെങ്കിൽ വീണ്ടും പരിശോധിക്കാൻ പറയുക.",raiseDispute:"വീണ്ടും പരിശോധിക്കുക",noAction:"ഇപ്പോൾ ഒന്നും ചെയ്യേണ്ടതില്ല. നില ഇവിടെ മാറും.",grievance:"ക്ലെയിം സഹായം",disputeTitle:"വീണ്ടും പരിശോധിക്കാൻ പറയുക",disputeDesc:"ക്ലെയിം {id}",rejectedClaim:"നിരസിച്ച ക്ലെയിം",explain:"എന്താണ് തെറ്റെന്ന് പറയുക",explainPlaceholder:"സംഭവിച്ചത് എഴുതുക. സഹായിക്ക് നിങ്ങൾക്കായി എഴുതാം.",explainHelp:"OTPയോ മുഴുവൻ ആധാർ നമ്പറോ എഴുതരുത്.",submitDispute:"അപേക്ഷ അയയ്ക്കുക",disputeSent:"അപേക്ഷ അയച്ചു",disputeSentText:"ക്ലെയിം വീണ്ടും പരിശോധിക്കും.",reference:"റഫറൻസ് നമ്പർ",returnClaim:"ക്ലെയിമിലേക്ക് മടങ്ങുക",
    errorClaims:"ക്ലെയിമുകൾ ലഭിച്ചില്ല. വീണ്ടും ശ്രമിക്കുക.",errorClaim:"ക്ലെയിം തുറന്നില്ല. വീണ്ടും ശ്രമിക്കുക.",errorTreatment:"ചികിത്സാ വിവരം അയച്ചില്ല. വീണ്ടും ശ്രമിക്കുക.",errorVerify:"ഡോക്ടർ പരിശോധന സൂക്ഷിച്ചില്ല. വീണ്ടും ശ്രമിക്കുക.",errorDispute:"അപേക്ഷ അയച്ചില്ല. വീണ്ടും ശ്രമിക്കുക.",dismiss:"സന്ദേശം അടയ്ക്കുക",otpHelp:"നിങ്ങളുടെ ഫോൺ കോഡ് 123456 ആണ്.",errorConfig:"ആപ്പ് ഇതുവരെ സെർവറുമായി ബന്ധിപ്പിച്ചിട്ടില്ല.",chooseFacility:"ക്ലിനിക്കോ ആശുപത്രിയോ തിരഞ്ഞെടുക്കുക",chooseFacilityHelp:"തൊഴിലാളി ചികിത്സ നേടിയ സ്ഥലം തിരഞ്ഞെടുക്കുക.",abhaFacility:"ABHA ബന്ധിപ്പിച്ചു",referralFacility:"ഡോക്ടർ പരിശോധന വേണം",treatmentCost:"ചികിത്സാ ചെലവ്",treatmentCostHelp:"തുക രൂപയിൽ നൽകുക.",scanSelected:"ചികിത്സാ വിവരം അയയ്ക്കുക",qrAlt:"തൊഴിലാളി ആരോഗ്യ ഐഡിയുടെ QR കോഡ്",claimAria:"ക്ലെയിം {id}, {status}, തുക {amount} രൂപ"
  },
  bn: {
    govt:"কেরালা সরকার",dept:"শ্রম ও দক্ষতা বিভাগ",appName:"শ্রমিক স্বাস্থ্য সেবা",appTag:"স্বাস্থ্য আইডি ও বিমা সহায়তা",helpline:"সহায়তা নম্বর",skip:"মূল অংশে যান",home:"হোম",services:"সেবা",claims:"আমার ক্লেম",help:"সহায়তা",safety:"আপনার OTP ও আধার নম্বর কাউকে বলবেন না।",footerLine:"কেরালা সরকারের শ্রম ও দক্ষতা বিভাগের সেবা।",quickLinks:"দরকারি লিংক",needHelp:"সাহায্য দরকার?",hours:"সোমবার–শনিবার, সকাল ৮টা–রাত ৮টা",copyright:"কেরালা সরকার",
    welcomeTag:"স্বাস্থ্য ও বিমা সহায়তা",welcomeTitle:"স্বাস্থ্য কার্ড ও ক্লেম, এক জায়গায়",welcomeBody:"শ্রমিক স্বাস্থ্য আইডি নিন, ক্লিনিকে দেখান এবং বিমার ক্লেম দেখুন।",chooseLanguage:"আপনার ভাষা বেছে নিন",newWorker:"আমার নতুন আইডি চাই",haveId:"আমার আইডি আছে",secureServices:"আপনার সেবা",onePlace:"সহজ ও নিরাপদ",digitalId:"স্বাস্থ্য আইডি কার্ড",digitalDesc:"ক্লিনিকে QR কার্ড দেখান।",treatmentHelp:"চিকিৎসায় সহায়তা",treatmentDesc:"দরকার হলে সঠিক হাসপাতালে যান।",claimTracking:"ক্লেমের অবস্থা",claimDesc:"ক্লেম যাচাই হচ্ছে, মঞ্জুর বা টাকা দেওয়া হয়েছে কি না দেখুন।",privacy:"আপনার পুরো আধার নম্বর এখানে দেখানো হয় না।",abhaLinked:"ABHA যুক্ত",abhaText:"স্বাস্থ্য রেকর্ড",aawazActive:"আওয়াজ সক্রিয়",aawazText:"শ্রমিক বিমা",claimHelp:"ক্লেম সহায়তা",claimHelpText:"অবস্থা ও অভিযোগ",
    back:"পিছনে যান",required:"দরকারি",registerTag:"নতুন শ্রমিক",registerTitle:"শ্রমিক স্বাস্থ্য আইডি নিন",registerDesc:"আধার ও ই-শ্রম কার্ড কাছে রাখুন।",step1:"আপনার তথ্য দিন",asOnCards:"কার্ড দেখে ঠিকভাবে লিখুন",aadhaar:"আধার নম্বর",aadhaarPlaceholder:"১২ সংখ্যার আধার নম্বর",aadhaarHelp:"শুধু পরিচয় যাচাই করতে এটি ব্যবহার করা হয়।",eshram:"ই-শ্রম নম্বর",eshramPlaceholder:"ই-শ্রম নম্বর লিখুন",step2:"আঙুলের ছাপ যাচাই করুন",fingerHelp:"আঙুলের ছাপ স্ক্যানার ব্যবহার করুন",capture:"আঙুলের ছাপ স্ক্যান করুন",captured:"আঙুলের ছাপ স্ক্যান হয়েছে",capturedHelp:"আঙুলের ছাপ পাওয়া গেছে",placeFinger:"স্ক্যানারে আঙুল রাখুন",consent:"স্বাস্থ্য ও বিমা সেবার জন্য এই তথ্য ব্যবহারে আমি সম্মত।",verify:"তথ্য যাচাই করে এগিয়ে যান",beforeBegin:"এগুলো কাছে রাখুন",ready1:"আধার কার্ড",ready2:"ই-শ্রম কার্ড",ready3:"রেকর্ডের সঙ্গে যুক্ত ফোন",callHelp:"সহায়তার জন্য ফোন করুন",
    loginTag:"আবার স্বাগত",loginTitle:"আপনার অ্যাকাউন্ট খুলুন",loginDesc:"ই-শ্রম নম্বর ও ফোনে আসা কোড লিখুন।",otp:"ফোন কোড (OTP)",otpPlaceholder:"ফোন কোড লিখুন",signIn:"আমার অ্যাকাউন্ট খুলুন",loginHint:"ফোন কোডটি ৬ সংখ্যার।",regFailTitle:"তথ্য যাচাই করা যায়নি",regFailText:"আধার ও ই-শ্রম নম্বর দেখে আবার চেষ্টা করুন।",loginFailTitle:"অ্যাকাউন্ট খোলা যায়নি",loginFailText:"ই-শ্রম নম্বর ও ফোন কোড দেখে আবার চেষ্টা করুন।",tryAgain:"আবার চেষ্টা করুন",returnHome:"হোমে যান",
    regDone:"আইডি তৈরি",verifiedTitle:"আপনার শ্রমিক আইডি তৈরি হয়েছে",linkedText:"স্বাস্থ্য ও বিমা সেবা যুক্ত হয়েছে।",workerId:"শ্রমিক আইডি",abhaId:"ABHA স্বাস্থ্য আইডি",aawazId:"আওয়াজ বিমা",linked:"যুক্ত",openDashboard:"এগিয়ে যান",
    dashboard:"আমার সেবা",welcome:"নমস্কার",dashboardDesc:"আপনি কী করতে চান?",verifiedAccount:"যাচাই হয়েছে",citizenServices:"একটি সেবা বেছে নিন",showId:"আমার স্বাস্থ্য আইডি দেখান",showIdText:"ক্লিনিকে এই QR কার্ড দেখান।",trackClaims:"আমার ক্লেম দেখুন",trackClaimsText:"অবস্থা ও টাকা দেওয়া হয়েছে কি না দেখুন।",healthRecords:"স্বাস্থ্য রেকর্ড",healthRecordsText:"যুক্ত চিকিৎসার রেকর্ড দেখুন।",findFacility:"হাসপাতাল খুঁজুন",findFacilityText:"কাছাকাছি চিকিৎসা খুঁজুন।",comingSoon:"শীঘ্রই আসছে",coverage:"আমার লিংক",accountCheck:"অ্যাকাউন্ট",active:"সক্রিয়",important:"মনে রাখুন",showBefore:"চিকিৎসা শুরুর আগে স্বাস্থ্য আইডি দেখান।",
    idTag:"আমার স্বাস্থ্য আইডি",idTitle:"ক্লিনিকে এই কার্ড দেখান",idDesc:"ক্লিনিক এই QR কোড স্ক্যান করতে পারে।",validFacilities:"যাচাই করা স্বাস্থ্য সেবা আইডি",clinicAction:"ক্লিনিকে",clinicActionText:"চিকিৎসার আগে এই কার্ড স্ক্যান করতে বলুন।",scan:"কার্ড স্ক্যান করুন",referralTag:"পরের ধাপ",referralTitle:"এই সরকারি হাসপাতালে যান",referralDesc:"ক্লেম এগোনোর আগে ডাক্তার চিকিৎসা যাচাই করবেন।",nearestHospital:"সবচেয়ে কাছের সরকারি হাসপাতাল",defaultHospital:"সরকারি তালুক হাসপাতাল, কোচি",referralDesk:"রেফারেল ডেস্কে যান",directions:"রাস্তা দেখতে মানচিত্র খুলুন",atHospital:"কী করবেন",hospital1:"শ্রমিক স্বাস্থ্য আইডি দেখান।",hospital2:"চিকিৎসার কাগজ দেখান।",hospital3:"ডাক্তারকে ক্লেম যাচাই করতে বলুন।",doctorVerify:"ডাক্তার যাচাই করেছেন",
    claimsTag:"আমার বিমা",claimsTitle:"আমার ক্লেম",claimsDesc:"আরও দেখতে ক্লেমে চাপ দিন।",records:"ক্লেম",loadingClaims:"ক্লেম লোড হচ্ছে…",noClaims:"এখনও কোনো ক্লেম নেই",noClaimsText:"ক্লিনিক পাঠানোর পরে নতুন ক্লেম এখানে দেখা যাবে।",claimAmount:"টাকার পরিমাণ",dateUnavailable:"তারিখ পাওয়া যায়নি",claimDetails:"ক্লেমের তথ্য",updated:"শেষ বদল",currentStatus:"এখনকার অবস্থা",progress:"কী হচ্ছে",submitted:"পাঠানো হয়েছে",checking:"যাচাই চলছে",approved:"মঞ্জুর",paid:"টাকা দেওয়া হয়েছে",rejected:"নামঞ্জুর",rejectionReason:"নামঞ্জুর হওয়ার কারণ",rejectedDefault:"বিমা অফিস এই ক্লেম মঞ্জুর করতে পারেনি।",availableAction:"আপনি কী করতে পারেন",disputeHelp:"তথ্য ভুল হলে আবার যাচাই করতে বলুন।",raiseDispute:"আবার যাচাই করতে বলুন",noAction:"এখন কিছু করতে হবে না। অবস্থা এখানে বদলাবে।",grievance:"ক্লেম সহায়তা",disputeTitle:"আবার যাচাই করতে বলুন",disputeDesc:"ক্লেম {id}",rejectedClaim:"নামঞ্জুর ক্লেম",explain:"কী ভুল হয়েছে বলুন",explainPlaceholder:"কী হয়েছে লিখুন। সহায়তাকারী আপনার হয়ে লিখতে পারেন।",explainHelp:"OTP বা পুরো আধার নম্বর লিখবেন না।",submitDispute:"অনুরোধ পাঠান",disputeSent:"অনুরোধ পাঠানো হয়েছে",disputeSentText:"আমরা ক্লেম আবার যাচাই করব।",reference:"রেফারেন্স নম্বর",returnClaim:"ক্লেমে ফিরে যান",
    errorClaims:"ক্লেম লোড হয়নি। আবার চেষ্টা করুন।",errorClaim:"ক্লেম খোলা যায়নি। আবার চেষ্টা করুন।",errorTreatment:"চিকিৎসার তথ্য পাঠানো যায়নি। আবার চেষ্টা করুন।",errorVerify:"ডাক্তারের যাচাই সেভ হয়নি। আবার চেষ্টা করুন।",errorDispute:"অনুরোধ পাঠানো যায়নি। আবার চেষ্টা করুন।",dismiss:"বার্তা বন্ধ করুন",otpHelp:"আপনার ফোন কোড 123456।",errorConfig:"অ্যাপটি এখনও সার্ভারের সঙ্গে যুক্ত নয়।",chooseFacility:"ক্লিনিক বা হাসপাতাল বেছে নিন",chooseFacilityHelp:"যেখানে শ্রমিকের চিকিৎসা হয়েছে, সেই জায়গা বেছে নিন।",abhaFacility:"ABHA যুক্ত",referralFacility:"ডাক্তারের যাচাই দরকার",treatmentCost:"চিকিৎসার খরচ",treatmentCostHelp:"টাকার পরিমাণ লিখুন।",scanSelected:"চিকিৎসার তথ্য পাঠান",qrAlt:"শ্রমিক স্বাস্থ্য আইডির QR কোড",claimAria:"ক্লেম {id}, {status}, পরিমাণ {amount} টাকা"
  }
};

const locales = { en: "en-IN", hi: "hi-IN", ml: "ml-IN", bn: "bn-IN" };
const I18nContext = createContext({ language: "en", t: (key) => key, locale: "en-IN" });

export function I18nProvider({ language, children }) {
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const value = useMemo(() => ({ language, locale: locales[language] || locales.en, t(key, vars) { let value = copy[language]?.[key] ?? copy.en[key] ?? key; Object.entries(vars || {}).forEach(([name, replacement]) => { value = value.replace(`{${name}}`, replacement); }); return value; } }), [language]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() { return useContext(I18nContext); }
export const languageOptions = [["en","English"],["hi","हिन्दी"],["ml","മലയാളം"],["bn","বাংলা"]];
